---
layout: cv
title: Scott Cannegieter Resume
---
# Scott Cannegieter
Accountant, Student, Friend.

<div id="webaddress">
<a href="scottcannegieter@gmail.com">scottcannegieter@gmail.com</a>
</div>


## Currently

Aspiring for an accounting internship this summer

### Specialized in

Accounting, Programming, Education, Team Work


### Research interests

Math, Numbers, Organization, Travel, Sports


## Education

`September 2014 - May 2018`
__Highland Highschool, Gilbert AZ__

`September 2018 - Now`
__Brigham Young Universtiy-Idaho, Rexburg ID__



## Awards

`2023`
Certified Commercial Driver's License, Class B, State of Idaho


## Occupation

`2023 - 2024`
__Driver Guide__, Juneau AK

- Gave guided tours to cruise passengers visiting Juneau, Alaska.
- Adapted to daily fluctuating schedules depending on tourist demand.

`1600`
__Flumes Operator__, Rexburg ID

- Worked overnight at the largeset potato warehouse/factory in eastern Idaho
- Oversaw the maintence and upkeeping of tens of thousands of dollars worth of equipment and machinery

<!-- ### Footer

Last updated: May 2013 -->